### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by santhosh3000** [WSU-4110/Pet-Care#1]
|FR10.  Homepage|
|---|
|**Goal**: The homepage will show the user friend’s post and pictures.
**Stakeholders:** User|
| **Description:** When a user goes to the homepage. They will see pictures / posts that friends made. They will also be able to make their own post on the homepage. |
| **Origin:** Based on initial project specification.|
| **Version:** 1.0  |  
|**Date:** October 5th, 2019 
|  **Priority:** 1 |

**Comment by HassanBachir** [comment]
Duplicate "About Us" in the left-side bar.
