### ISSUE TITLE
Contact Us UI and Functionality

### ISSUE THREAD

**Issue by LaithR** [WSU-4110/Pet-Care#12]
|FR:13 Contact us UI and functionality|
|---|
|**Goal**: Build the user interface for the “Contact Us” page and make it functional to be used.
**Stakeholders:** Users|
| **Description:** When a user comes into the “Contact Us” page, they are greeted and thanked for using the Pet Care Social media platform and they will be prompted to fill out a 3-4 free text form field and click on the submit button. They will get a confirmation email. |
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** October 5th, 2019|
  **Priority:** 1 |

**Comment by OmarFaruqRahman** [comment]
Looks Good
