### ISSUE TITLE
Donations Tab and Feature

### ISSUE THREAD

**Issue by LaithR** [WSU-4110/Pet-Care#15]
|FR15 : Donations Tab and Feature |
|---|
|**Goal**: Embed a donations tab in the website.
**Stakeholders:** Users|
| **Description:** Implement a donate button and direct donation payments from Mastercard/Visa, Apple Pay, Google Pay, or PayPal. It will be secure. |
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** November 5th, 2019 |
  **Priority:** 3 |

**Comment by HassanBachir** [comment]
PayPal extension failed to load.
