### ISSUE TITLE
Google Maps API

### ISSUE THREAD

**Issue by LaithR** [WSU-4110/Pet-Care#16]
|Non-Functional Feature 5: Google Maps API|
|---|
|**Goal**: Embed a Google Maps API in a website tab
**Stakeholders:** Users|
| **Description:** Embed a Google Maps API in one of the website tabs for users to be able to find the nearest vet, park or any other pet attraction they are looking for.|
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |
|**Date:** November 20th, 2019|
  **Priority:** 4 |

**Comment by HassanBachir** [comment]
API won't work with a specific address format (SAF)
