### ISSUE TITLE
                                              Sign In/Login

### ISSUE THREAD

**Issue by Mahir898** [WSU-4110/Pet-Care#3]
|FR1. 
|---|
|**Goal**: To make the user sign in for the website.
**Stakeholders:** Users|
| **Description:**  This will be a page where the users will be prompted to sign up for the website by giving email address and password.They will use the same information to login afterwards. 
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 10/05/2019  
|  **Priority:** 1 |

**Comment by HassanBachir** [comment]
Password validation wasn't working
