### ISSUE TITLE
Lost and Found

### ISSUE THREAD

**Issue by OmarFaruqRahman** [WSU-4110/Pet-Care#4]
|Functional Feature 5 : Lost and Found|
|---|
|**Goal**: The user will be able to look for their lost pet.
**Stakeholders:** Pet Owners, Website users|
| **Description:**There shall be a section on the website where pet owners can log their lost pets. Through community search they will be able to look for their lost pet. There will also be a section on reporting the found animals. |
| **Origin:** One of the key ideas behind the pet care website |
| **Version:** 1.0  |  
|**Date:** 10/5/2019 | 
|  **Priority:** 1 |

**Comment by HassanBachir** [comment]
File upload from computer doesn't work. Only accepts URLs
