### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by Mahir898** [WSU-4110/Pet-Care#8]
|FR2. |
|---|
|**Goal**: To create a profile for the user to use the system.
**Stakeholders:** Users|
| **Description:**   The system would  require the user  to create a profile to use the system. The user needs to create a user account using First Name , Last Name ,owner’s address , phone number etc . 
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |  
|**Date:** 10/15/2019  
|  **Priority:** 1 |

**Comment by OmarFaruqRahman** [comment]
fix it ..not the correct format

**Comment by Mahir898** [comment]
> fix it ..not the correct format

done
